version: "3"
services:
    web:
        build: .
        volumes:
        - .:/application
        environment:
            FLASK_DEBUG: 1
            FLASK_ENV: development
        ports:
            - '5000:5000'
        entrypoint:
            - python
            - app.py
            - --host=0.0.0.0